#! /bin/sh

#spc monitor eDP-1 -d TERM WEB CODE MSIC EDIT &
#bspc monitor HDMI-1 -d TERM WEB CODE MSIC EDIT &
bspc monitor eDP-1 -d TERM WEB CODE MISC EDIT CHAT DISCORD MUSIC &
xrandr --output eDP-1 --mode 1920x1080 --rotate normal --output HDMI-1 --primary --rotate normal --left-of eDP-1 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config focused_border_color "#928374"
bspc config normal_border_color "#282828"

feh --bg-fill ~/wallpaper/wallpapers/gruvbox/waterfall.jpg
ibus-daemon -drx &
polybar main&
polybar external&
picom &
